name: Check NTP Drift Between Two Servers

description: |
  GitHub Action to verify time drift between two NTP servers using the `rkik` Rust crate.

inputs:
  server_a:
    description: "First NTP server (e.g. 0.fr.pool.ntp.org)"
    required: true
  server_b:
    description: "Second NTP server (e.g. 1.fr.pool.ntp.org)"
    required: true
  max_drift_ms:
    description: "Maximum allowed drift in milliseconds"
    required: false
    default: "50"

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env

    - name: Install rkik
      shell: bash
      run: |
        cargo install rkik --version 0.5.0 --force

    - name: Compare NTP servers and check drift
      shell: bash
      run: |
        source $HOME/.cargo/env
        echo "Comparing ${{ inputs.server_a }} and ${{ inputs.server_b }}"
        output=$(rkik --compare "${{ inputs.server_a }}" "${{ inputs.server_b }}" --format json)
        echo "Raw output: $output"
        drift=$(echo "$output" | jq -r '.difference_ms')
        threshold="${{ inputs.max_drift_ms }}"
        echo "Observed drift: $drift ms"
        echo "Allowed drift: $threshold ms"
        awk -v d="$drift" -v t="$threshold" 'BEGIN { exit (d > t ? 1 : 0) }'
